curl -X PUT -d '{"title" : "1", "preamble" : "Post", "body" : "Of news", "url" : "http://www.google.com"}' http://localhost:8080/news
curl -X PUT -d '{"title" : "2", "preamble" : "Post", "body" : "Of news", "url" : "http://www.google.com"}' http://localhost:8080/news
curl -X PUT -d '{"title" : "3", "preamble" : "Post", "body" : "Of news", "url" : "http://www.google.com"}' http://localhost:8080/news
curl -X PUT -d '{"title" : "4", "preamble" : "Post", "body" : "Of news", "url" : "http://www.google.com"}' http://localhost:8080/news
curl -X PUT -d '{"title" : "5", "preamble" : "Post", "body" : "Of news", "url" : "http://www.google.com"}' http://localhost:8080/news
curl -X PUT -d '{"title" : "6", "preamble" : "Post", "body" : "Of news", "url" : "http://www.google.com"}' http://localhost:8080/news
curl -X PUT -d '{"title" : "7", "preamble" : "Post", "body" : "Of news", "url" : "http://www.google.com"}' http://localhost:8080/news
curl -X PUT -d '{"title" : "8", "preamble" : "Post", "body" : "Of news", "url" : "http://www.google.com"}' http://localhost:8080/news
curl -X PUT -d '{"title" : "9", "preamble" : "Post", "body" : "Of news", "url" : "http://www.google.com"}' http://localhost:8080/news
curl -X PUT -d '{"title" : "10", "preamble" : "Post", "body" : "Of news", "url" : "http://www.google.com"}' http://localhost:8080/news
curl -X PUT -d '{"title" : "11", "preamble" : "Post", "body" : "Of news", "url" : "http://www.google.com"}' http://localhost:8080/news
curl -X PUT -d '{"title" : "12", "preamble" : "Post", "body" : "Of news", "url" : "http://www.google.com"}' http://localhost:8080/news
curl -X PUT -d '{"title" : "13", "preamble" : "Post", "body" : "Of news", "url" : "http://www.google.com"}' http://localhost:8080/news
curl -X PUT -d '{"title" : "14", "preamble" : "Post", "body" : "Of news", "url" : "http://www.google.com"}' http://localhost:8080/news
curl -X PUT -d '{"title" : "15", "preamble" : "Post", "body" : "Of news", "url" : "http://www.google.com"}' http://localhost:8080/news
curl -X PUT -d '{"title" : "16", "preamble" : "Post", "body" : "Of news", "url" : "http://www.google.com"}' http://localhost:8080/news
curl -X PUT -d '{"title" : "17", "preamble" : "Post", "body" : "Of news", "url" : "http://www.google.com"}' http://localhost:8080/news
curl -X PUT -d '{"title" : "18", "preamble" : "Post", "body" : "Of news", "url" : "http://www.google.com"}' http://localhost:8080/news
curl -X PUT -d '{"title" : "19", "preamble" : "Post", "body" : "Of news", "url" : "http://www.google.com"}' http://localhost:8080/news
curl -X PUT -d '{"title" : "20", "preamble" : "Post", "body" : "Of news", "url" : "http://www.google.com"}' http://localhost:8080/news
curl -X PUT -d '{"title" : "21", "preamble" : "Post", "body" : "Of news", "url" : "http://www.google.com"}' http://localhost:8080/news
curl -X PUT -d '{"title" : "22", "preamble" : "Post", "body" : "Of news", "url" : "http://www.google.com"}' http://localhost:8080/news
curl -X PUT -d '{"title" : "23", "preamble" : "Post", "body" : "Of news", "url" : "http://www.google.com"}' http://localhost:8080/news
curl -X PUT -d '{"title" : "24", "preamble" : "Post", "body" : "Of news", "url" : "http://www.google.com"}' http://localhost:8080/news
curl -X PUT -d '{"title" : "25", "preamble" : "Post", "body" : "Of news", "url" : "http://www.google.com"}' http://localhost:8080/news
curl -X PUT -d '{"title" : "26", "preamble" : "Post", "body" : "Of news", "url" : "http://www.google.com"}' http://localhost:8080/news
curl -X PUT -d '{"title" : "27", "preamble" : "Post", "body" : "Of news", "url" : "http://www.google.com"}' http://localhost:8080/news
curl -X PUT -d '{"title" : "28", "preamble" : "Post", "body" : "Of news", "url" : "http://www.google.com"}' http://localhost:8080/news
curl -X PUT -d '{"title" : "29", "preamble" : "Post", "body" : "Of news", "url" : "http://www.google.com"}' http://localhost:8080/news
curl -X PUT -d '{"title" : "30", "preamble" : "Post", "body" : "Of news", "url" : "http://www.google.com"}' http://localhost:8080/news
curl -X PUT -d '{"title" : "31", "preamble" : "Post", "body" : "Of news", "url" : "http://www.google.com"}' http://localhost:8080/news
curl -X PUT -d '{"title" : "32", "preamble" : "Post", "body" : "Of news", "url" : "http://www.google.com"}' http://localhost:8080/news